### PR TITLE
Post map

### PR DESCRIPTION
**Pull request by droyad**
Not sure if you want to include this one. Gives the option to apply a post map step through arguments

### CODE REVIEW

**Comment by kkozmic** [comment]
do you have a need to dynamically sort collection?
As in you don't know how you want it sorted until you call to mapper?

I think I would prefer using custom IConversionPattern for that

**Comment by droyad** [comment]
Pretty much, it's mapping a DTO to a (WPF) VM. One of the properties of the dto we are mapping needs to be sorted, so it gets around this sort of thing:

var vm = _mapper.Convert(dto)
vm.Items = vm.Items.OrderBy(i => i.Name).ToObservableCollection()

**Comment by kkozmic** [comment]
wouldn't implementing IConversionPattern&lt;IEnumerable&lt;string&gt;,ObservableCollection&lt;string&gt;&gt; and doing the sorting there be a better option?

**Comment by droyad** [comment]
Possibly, I'll try it out, didn't know that was an option :) (#lazyweb)
I think my desire was to override the behaviour inline to make it clearer

**Comment by kkozmic** [comment]
putting a custom conversion pattern is like specifying a convention, "Every time we map IEnumerable to ObservableCollection we sort it". Approaching it from that angle, it is explicit enough IMO. Plus it has the benefit of being applied automatically so you don't have to worry about doing it every time manually and you avoid subtle bugs where a developer forgets to put the sorting in, and the resulting list ends up being in wrong order.

There are some things coming for later (possibly post 1.0 version) that should make it simpler to apply those things in a slightly more granular way by using multiple mapper configurations

**Comment by droyad** [comment]
hmm... thinking ahead, I could pass the field to sort by in as an argument somehow.

**Comment by kkozmic** [comment]
I'm just interested how much you really need that. Wouldn't sorting by item.ToString() or via default comparer on the type suffice?

Alternatively it seems like it might be one of cases where post-mapping step could be beneficial. That's another feature/hook I'm considering...

**Comment by droyad** [comment]
The only scenario I can think of ATM is sorting to a user preference when an UI driven sort isn't available.

**Comment by kkozmic** [comment]
ok I get your point.

I will keep that in mind as a scenario, although I think the ultimate solution will be different. This one is too "magic value" driven.

Plus it's quite easy to do it with the code from the pull request by adding a custom IConversionPattern that calls to your modified CollectionConversionHelper rather than the built in one.

**Pull request closed without merging**
